// Everyone you can talk to. Look at them to hear them; press E or click for more.

export const GUARDS = [
  {
    id: 'aldric',
    kind: 'knight',
    name: 'Ser Aldric the Unsleeping',
    path: [[-2.0, -7]],
    facing: 0,
    lines: [
      'Halt. ...No. Go on, pilgrim. The castle expects everyone, sooner or later.',
      'Keep to the middle of the steps. The edges remember the ones who fell.',
      'Nine hundred nights at this post. I do not recall sleeping. I do not recall wanting to.',
    ],
  },
  {
    id: 'lamplighter',
    kind: 'hooded',
    name: 'The Lamplighter',
    path: [[1.3, -9], [1.3, -48]],
    speed: 0.9,
    lines: [
      'Mind the torches. They burn orange so the blue light cannot follow you in.',
      'I light them at dusk. It is always dusk.',
      'If the Eye blinks while you are on the causeway... try not to be on the causeway.',
    ],
  },
  {
    id: 'grisel',
    kind: 'knight',
    name: 'Ser Grisel',
    path: [[-1.3, -30], [-1.3, -72]],
    speed: 1.2,
    lines: [
      'Clank. Clank. Clank. Forgive me. The armour talks when I walk.',
      'The castle had a name once. The Eye took it, along with the stars.',
      'The goblins at the Tankard sing all night. The Eye cannot abide them. I envy them.',
    ],
  },
  {
    id: 'wick',
    kind: 'hooded',
    name: 'Brother Wick',
    path: [[1.4, -56], [1.4, -93]],
    speed: 0.8,
    lines: [
      'Shhh. It is listening. It is always listening.',
      'We wear hoods so that it cannot learn our faces.',
      'Climb, if you must. The gate does not open. It only waits.',
    ],
  },
  {
    id: 'ossian',
    kind: 'knight',
    name: 'Ser Ossian',
    path: [[-11, -103], [11, -103]],
    speed: 1.1,
    lines: [
      'Patrol. Turn. Patrol. Turn. The stones wear down. I do not.',
      'Look up if you like. Everyone does, once.',
    ],
  },
  {
    id: 'vane',
    kind: 'knight',
    name: 'Ser Vane, Captain of the Vigil',
    path: [[-2.6, -109.5]],
    facing: 0.25,
    lines: [
      'I am Vane, Captain of the Vigil. We watch the Eye, and the Eye watches us.',
      'The gate has not opened in a hundred years. Whatever is inside has not asked to leave.',
      'Go back down to the Tankard, pilgrim. Drink something warm. Forget the colour blue.',
    ],
  },
  {
    id: 'cantor',
    kind: 'hooded',
    name: 'The Pale Cantor',
    path: [[2.6, -109.5]],
    facing: -0.25,
    lines: [
      '~ Oculus, oculus... dormi, dormi... ~',
      'It must never close. If it closes, it will dream. If it dreams, we will be the dream.',
      'Your eyes are very clear. Keep them that way.',
    ],
  },
];

// pose: cheer | toast | sit | dance | lean | keeper
export const GOBLINS = [
  {
    id: 'snaggle',
    name: 'Snaggle Grinmug',
    position: [24, 0.95, 4],
    rotation: -0.4,
    pose: 'cheer',
    onTable: true,
    lines: [
      'OI! OI! Another round for the tall pink one!',
      'Checkered hats! Proper motley, this is. We are the Tankard Fools, founded last Tuesday!',
      'The Eye can\'t see through a good head of foam. That\'s science, that is.',
    ],
  },
  {
    id: 'nib',
    name: 'Nib Kettleback',
    position: [22.2, 0, 5.6],
    rotation: 2.3,
    pose: 'cheer',
    skin: '#6d9a36',
    tunic: '#6a2a1c',
    lines: ['*HIC* ...you want some? It\'s mostly ale. Mostly.', 'To the Eye! May it get something in it!'],
  },
  {
    id: 'wort',
    name: 'Wort the Loud',
    position: [29, 0.08, 15.6],
    rotation: Math.PI,
    pose: 'sit',
    skin: '#4f7d2a',
    tunic: '#5a4a1a',
    lines: ['WHAT? I SAID WHAT? OH! CHEERS!', 'I\'ve been sat on this stool since the bridge was new.'],
  },
  {
    id: 'pip',
    name: 'Pip Jangleboots',
    position: [29, 0, 8],
    rotation: 0,
    pose: 'dance',
    skin: '#7aa33f',
    tunic: '#3a3a5a',
    lines: ['Dance with me! Left foot, right foot, jingle jingle!', 'The bells on the hat keep off ghosts. And tax collectors.'],
  },
  {
    id: 'grubnik',
    name: 'Grubnik Tapfoot, Keeper',
    position: [39.3, 0, 10],
    rotation: -Math.PI / 2,
    pose: 'keeper',
    skin: '#5a8a30',
    tunic: '#d8d0b8',
    lines: [
      'Welcome to the Grinning Tankard! Mind the teeth. They\'re decorative.',
      'House special: Bog Stout. Brewed with real bog.',
      'Knights come down off the causeway some nights. We make \'em take the helmets off. Can\'t drink through a visor.',
    ],
  },
  {
    id: 'mogg',
    name: 'Mogg',
    position: [21.2, 0, 18.4],
    rotation: Math.PI / 2 - 0.2,
    pose: 'toast',
    skin: '#608f2c',
    tunic: '#2e4a2a',
    lines: ['To us! To ale! To not being up THERE!', 'Brisket owes me three pints and a tooth.'],
  },
  {
    id: 'brisket',
    name: 'Brisket',
    position: [23.2, 0, 18.4],
    rotation: -Math.PI / 2 - 0.2,
    pose: 'toast',
    skin: '#6f9a3a',
    tunic: '#6a3a1a',
    phase: 1.6,
    lines: ['Clink! Ha! Clink again! CLINK!', 'Mogg\'s lying about the tooth.'],
  },
  {
    id: 'fennick',
    name: 'Old Fennick',
    position: [34.8, 0, -1.6],
    rotation: -0.6,
    pose: 'lean',
    skin: '#57803a',
    tunic: '#4a3a2a',
    lines: ['Them barrels is full of courage. The liquid kind.', 'Saw the Eye blink once. Whole causeway went quiet as fish.'],
  },
];
