// Verses carved into rune stones, and whispers the Hollow leave behind.
export const VERSES = [
  ['The Crimson Moon', 'She rose red the night the last king wept,\nand has not set her colour since.'],
  ['Of the Hollow', 'They carry lanterns for the ones not yet found.\nDo not follow them. Do not stop them.'],
  ['Ashfall', 'The forest did not burn. It remembered burning,\nand became ash out of grief.'],
  ['The Bell Without a Tower', 'You will hear it toll across the wastes.\nNo one has found the bell. No one has found the ringer.'],
  ['Inscription, Worn', 'HERE WE BURIED OUR NAMES\nSO THE DARK WOULD NOT CALL US BY THEM'],
  ['The Chapel Rule', 'Light a candle for every face you forget.\nThe chapels are very bright.'],
  ['Soul Crystal', 'Each glimmer in the deep stone was a traveller.\nThey are not trapped. They are resting.'],
  ['Ravens', 'Count the ravens above you.\nIf there is one more than yesterday, be kind to it.'],
  ['The Veil', 'At night the sky tears a little.\nWhat looks down through it is only curious.'],
  ['Marsh Song', 'The water is black because it is deep,\nand deep because it is full of lanterns.'],
  ['On Building', 'Every wall you raise here is a promise\nthat someone will be sheltered from the ash.'],
  ['The Obelisks', 'They point at the moon.\nThey are waiting for her to notice.'],
  ['Wraithwood', 'The pale trees glow because they are dreaming.\nWalk quietly under them.'],
  ['The Bone Colossus', 'It lay down in the wastes to sleep a thousand years.\nIt has been nine hundred and ninety-nine.'],
  ['A Prayer', 'Grant me a roof, a candle,\nand a door that opens only outward.'],
  ['Inscription, Scratched', 'there is no ending here\nthere is only further'],
  ['Of Obsidian', 'Black glass, cooled from a mountain\'s last breath.\nIt shows your face as it will be.'],
  ['The Wanderer', 'You were not summoned. You were not chosen.\nYou simply walked in. The realm is glad.'],
  ['Bloodroot', 'It blooms where something was buried with love.\nThe Blighted Wood is full of it.'],
  ['The Last Monk', 'He carved the rune stones so the dark would have\nsomething to read, and leave the living alone.'],
  ['Witchfire', 'Green flame feeds on memory.\nWarm your hands, not your heart.'],
  ['Ghostcaps', 'Where they glow, someone once sat and rested.\nSit a while. It is permitted.'],
  ['Midnight', 'At the Witching Hour the realm is most itself.\nIt is not cruel. It is only honest.'],
  ['Inscription, Faded', 'LEAVE SOMETHING BEAUTIFUL\nIT IS THE ONLY TOLL'],
];

export const WHISPERS = [
  'You hear your name, spoken kindly, very far away.',
  'Something in the dark wishes you a safe road.',
  'A lantern bobs at the edge of sight, then is gone.',
  'The Hollow do not like to be seen. They like to be remembered.',
  'The ash smells faintly of old incense.',
  'Somewhere, a bell tolls for no one in particular.',
  'The moon watches you build. She approves.',
  'A cold wind passes through you, and moves on politely.',
];
